### PR TITLE
fix: add mail for Deparment; add `特别支持`; set `白金赞助` as Single Line Benefits Levels

### LINKED ISSUE #201: 部门简介新增官方电邮地址
## 原始数据

[腾讯企业邮箱][1]通讯录

## 目标数据

https://kaiyuanshe.feishu.cn/base/UaJ6b4MtcaywOwsaT7ecyiQuntc?table=tblFRxhndo7SX4a7&view=vewTLsAEW9

## 目标组件

https://github.com/kaiyuanshe/kaiyuanshe.github.io/blob/3e1d60cd4305923dd9b9e9761ab54611445187d7/components/Department/Card.tsx#L14-L53

[1]: https://exmail.qq.com/

### LINKED ISSUE #214: COSCon 官网更新  2023 年赞助信息

### PR DESCRIPTION
**Pull request by stevending1st**
Checklist（清单）:

- [x] Labels
- [ ] Assignees
- [x] Reviewers

Closes #214
Closes #201

### CODE REVIEW

File: components/Department/Card.tsx [hunk 1]
```diff
@@ -44,10 +45,18 @@ export const GroupCard: FC<GroupCardProps> = ({
...
       {summary}
     </p>
+    {email && (
+      <dl className="mt-1 d-flex align-items-start">
+        <dt className="me-1">E-mail:</dt>
+        <dd>
+          <a href={email + ''}>{(email + '')?.split(':')[1]}</a>
+        </dd>
+      </dl>
+    )}
```
Comment (TechQuery) [inline components/Department/Card.tsx:60]:
```suggestion
    {email && (
      <dl className="mt-1 d-flex align-items-start">
        <dt className="me-1">E-mail:</dt>
        <dd>
          <a href={email + ''}>{(email + '').split(':')[1]}</a>
        </dd>
      </dl>
    )}
```
放简介上方

**Review by TechQuery — CHANGES_REQUESTED** [review]

**Review by TechQuery — APPROVED** [review]
